### ISSUE TITLE
can you add this mod and library on fabric minecraft 1.21.7?

### ISSUE THREAD

**Issue by Nikolas1480** [VillagerUnknown/FlatulenceUpdate#16]
i tried to modify this mod on 1.21.7, but i got some errors like java.lang.NoSuchMethodError: 'net.minecraft.class_1937 net.minecraft.class_1297.method_5770()' (fabric 1.21.7) and sometimes i got kicked from singleplayer world with description Exception in server tick loop

**Comment by VillagerUnknown** [comment]
I have plans to update all of my mods above 1.21.1

**Comment by Nikolas1480** [comment]
your mods can be updated above 1.21.5? like i want on 1.21.7 i saw on modrinth your mods are  on minecraft vesrsions 1.21.1-1.21.5

> I have plans to update all of my mods above 1.21.1

**Comment by VillagerUnknown** [comment]
Yes, I'm currently working on updating and re-releasing my 1.21.1 mods to the latest versions. I'm just getting over some IRL stuff atm so it's taking me a lot longer than I planned. You'll have it on 1.21.7 but I don't know when.
